/**
 * ScriptPlayground — unit tests for the code generator logic.
 *
 * We test the pure generateCode() function by extracting its logic here.
 * Run with:  npx jest  (or add jest to package.json)
 *
 * Tests cover:
 *  1. Empty steps → placeholder comment
 *  2. goto action → correct await page.goto(...)
 *  3. fill action with CSS selector
 *  4. fill action with placeholder selector method
 *  5. click with text selector
 *  6. click with data-testid
 *  7. click with XPath
 *  8. click with ARIA role
 *  9. sleep action
 * 10. screenshot action
 * 11. getText action
 * 12. waitForSelector
 * 13. scroll
 * 14. scrollPage - down / up / px
 * 15. comments are emitted as // Step N: <comment>
 * 16. press key action
 * 17. selectOption
 * 18. check / uncheck
 * 19. waitForURL
 * 20. waitForNetIdle
 * 21. log message action
 * 22. getAttribute
 * 23. uploadFile
 * 24. reload / goBack
 * 25. Multiple steps produce blank-line separators
 */

// ─── Inline the code generator (mirrors ScriptPlayground.jsx) ─────────────────

const SELECTOR_METHODS = [
  { value: 'css',         build: (v) => v },
  { value: 'id',          build: (v) => `#${v.replace(/^#/, '')}` },
  { value: 'text',        build: (v) => `text=${v}` },
  { value: 'testid',      build: (v) => `[data-testid="${v}"]` },
  { value: 'placeholder', build: (v) => `[placeholder="${v}"]` },
  { value: 'xpath',       build: (v) => `xpath=${v}` },
  { value: 'role',        build: (v) => {
    const [role, name] = v.split(':')
    return name ? `role=${role.trim()}[name="${name.trim()}"]` : `role=${v}`
  }},
]
const SELECTOR_MAP = Object.fromEntries(SELECTOR_METHODS.map((m) => [m.value, m]))

function generateCode(steps) {
  if (steps.length === 0) return '// No steps added yet.\n// Use the Playground tab to build your automation visually.'

  const lines = [
    '// ═══════════════════════════════════════════════════════════════════════════',
    '// Auto-generated by ScriptPlayground — feel free to edit!',
    '// ═══════════════════════════════════════════════════════════════════════════',
    '',
  ]

  steps.forEach((step, i) => {
    const comment = step.comment?.trim()
    const label = comment || step.action
    lines.push(`// Step ${i + 1}: ${label}`)

    const selectorMethod = SELECTOR_MAP[step.selectorMethod || 'css']
    const rawSelector = step.selector?.trim() || ''
    const selector = rawSelector ? selectorMethod.build(rawSelector) : ''

    switch (step.action) {
      case 'goto':
        lines.push(`await page.goto('${step.value || ''}', { waitUntil: 'domcontentloaded' });`)
        break
      case 'goBack':
        lines.push(`await page.goBack();`)
        break
      case 'reload':
        lines.push(`await page.reload({ waitUntil: 'domcontentloaded' });`)
        break
      case 'waitForURL':
        lines.push(`await page.waitForURL('${step.value || ''}', { timeout: 15000 });`)
        break
      case 'click':
        lines.push(`await page.click('${selector}');`)
        break
      case 'dblclick':
        lines.push(`await page.dblclick('${selector}');`)
        break
      case 'hover':
        lines.push(`await page.hover('${selector}');`)
        break
      case 'scroll':
        lines.push(`await page.locator('${selector}').scrollIntoViewIfNeeded();`)
        break
      case 'scrollPage': {
        const dir = step.value?.trim()
        if (!dir || dir === 'down') lines.push(`await page.evaluate(() => window.scrollBy(0, window.innerHeight));`)
        else if (dir === 'up') lines.push(`await page.evaluate(() => window.scrollBy(0, -window.innerHeight));`)
        else if (/^\d+$/.test(dir)) lines.push(`await page.evaluate(() => window.scrollBy(0, ${dir}));`)
        else lines.push(`await page.evaluate(() => window.scrollBy(0, window.innerHeight)); // direction: ${dir}`)
        break
      }
      case 'fill':
        lines.push(`await page.fill('${selector}', '${(step.value || '').replace(/'/g, "\\'")}');`)
        break
      case 'press':
        lines.push(`await page.press('${selector}', '${step.value || 'Enter'}');`)
        break
      case 'selectOption':
        lines.push(`await page.selectOption('${selector}', '${step.value || ''}');`)
        break
      case 'check':
        lines.push(`await page.check('${selector}');`)
        break
      case 'uncheck':
        lines.push(`await page.uncheck('${selector}');`)
        break
      case 'clearInput':
        lines.push(`await page.fill('${selector}', '');`)
        break
      case 'uploadFile':
        lines.push(`await page.setInputFiles('${selector}', '${step.value || ''}');`)
        break
      case 'waitForSelector':
        lines.push(`await page.waitForSelector('${selector}', { timeout: 10000 });`)
        break
      case 'waitForHidden':
        lines.push(`await page.waitForSelector('${selector}', { state: 'hidden', timeout: 10000 });`)
        break
      case 'sleep':
        lines.push(`await sleep(${parseInt(step.value) || 1000});`)
        break
      case 'waitForNetIdle':
        lines.push(`await page.waitForLoadState('networkidle');`)
        break
      case 'getText': {
        const varName = step.value?.trim() || `text_${i + 1}`
        lines.push(`const ${varName} = await page.textContent('${selector}');`)
        lines.push(`log.info(\`${varName}: \${${varName}}\`);`)
        break
      }
      case 'getAttribute': {
        const attrName = step.value?.trim() || 'href'
        const varName = `attr_${i + 1}`
        lines.push(`const ${varName} = await page.getAttribute('${selector}', '${attrName}');`)
        lines.push(`log.info(\`${attrName}: \${${varName}}\`);`)
        break
      }
      case 'screenshot':
        lines.push(`await page.screenshot({ path: '${step.value || '/tmp/screenshot.png'}', fullPage: true });`)
        lines.push(`log.success('Screenshot saved to ${step.value || '/tmp/screenshot.png'}');`)
        break
      case 'log':
        lines.push(`log.info('${(step.value || '').replace(/'/g, "\\'")}');`)
        break
      default:
        lines.push(`// [unknown action: ${step.action}]`)
    }

    lines.push('')
  })

  return lines.join('\n')
}

// ─── Helpers ──────────────────────────────────────────────────────────────────
function step(overrides) {
  return {
    action: 'goto',
    selector: '',
    selectorMethod: 'css',
    value: '',
    comment: '',
    ...overrides,
  }
}

// ─── Tests ────────────────────────────────────────────────────────────────────
describe('generateCode()', () => {
  test('1. empty steps → placeholder comment', () => {
    const out = generateCode([])
    expect(out).toContain('// No steps added yet.')
    expect(out).toContain('Playground tab')
  })

  test('2. goto → correct page.goto', () => {
    const out = generateCode([step({ action: 'goto', value: 'https://example.com' })])
    expect(out).toContain("await page.goto('https://example.com', { waitUntil: 'domcontentloaded' });")
  })

  test('3. fill with CSS selector', () => {
    const out = generateCode([step({ action: 'fill', selector: '#email', selectorMethod: 'css', value: 'user@test.com' })])
    expect(out).toContain("await page.fill('#email', 'user@test.com');")
  })

  test('4. fill with placeholder selector method', () => {
    const out = generateCode([step({ action: 'fill', selector: 'Enter email', selectorMethod: 'placeholder', value: 'hello@world.com' })])
    expect(out).toContain("await page.fill('[placeholder=\"Enter email\"]', 'hello@world.com');")
  })

  test('5. click with text selector', () => {
    const out = generateCode([step({ action: 'click', selector: 'Sign In', selectorMethod: 'text' })])
    expect(out).toContain("await page.click('text=Sign In');")
  })

  test('6. click with data-testid', () => {
    const out = generateCode([step({ action: 'click', selector: 'login-btn', selectorMethod: 'testid' })])
    expect(out).toContain("await page.click('[data-testid=\"login-btn\"]');")
  })

  test('7. click with XPath', () => {
    const out = generateCode([step({ action: 'click', selector: '//button[text()="Go"]', selectorMethod: 'xpath' })])
    expect(out).toContain("await page.click('xpath=//button[text()=\"Go\"]');")
  })

  test('8. click with ARIA role (role:name)', () => {
    const out = generateCode([step({ action: 'click', selector: 'button:Submit', selectorMethod: 'role' })])
    expect(out).toContain("await page.click('role=button[name=\"Submit\"]');")
  })

  test('8b. click with ARIA role (no name)', () => {
    const out = generateCode([step({ action: 'click', selector: 'button', selectorMethod: 'role' })])
    expect(out).toContain("await page.click('role=button');")
  })

  test('9. sleep with value', () => {
    const out = generateCode([step({ action: 'sleep', value: '3000' })])
    expect(out).toContain('await sleep(3000);')
  })

  test('9b. sleep with invalid value → defaults to 1000', () => {
    const out = generateCode([step({ action: 'sleep', value: 'abc' })])
    expect(out).toContain('await sleep(1000);')
  })

  test('10. screenshot with custom path', () => {
    const out = generateCode([step({ action: 'screenshot', value: '/tmp/my.png' })])
    expect(out).toContain("await page.screenshot({ path: '/tmp/my.png', fullPage: true });")
    expect(out).toContain("log.success('Screenshot saved to /tmp/my.png');")
  })

  test('10b. screenshot without path → default path', () => {
    const out = generateCode([step({ action: 'screenshot', value: '' })])
    expect(out).toContain('/tmp/screenshot.png')
  })

  test('11. getText → const + log', () => {
    const out = generateCode([step({ action: 'getText', selector: 'h1', selectorMethod: 'css', value: 'heading' })])
    expect(out).toContain("const heading = await page.textContent('h1');")
    expect(out).toContain('log.info(`heading: ${heading}`);')
  })

  test('12. waitForSelector', () => {
    const out = generateCode([step({ action: 'waitForSelector', selector: '.modal', selectorMethod: 'css' })])
    expect(out).toContain("await page.waitForSelector('.modal', { timeout: 10000 });")
  })

  test('13. scroll into view', () => {
    const out = generateCode([step({ action: 'scroll', selector: '#footer', selectorMethod: 'id' })])
    expect(out).toContain("await page.locator('#footer').scrollIntoViewIfNeeded();")
  })

  test('14a. scrollPage down', () => {
    const out = generateCode([step({ action: 'scrollPage', value: 'down' })])
    expect(out).toContain('window.scrollBy(0, window.innerHeight)')
  })

  test('14b. scrollPage up', () => {
    const out = generateCode([step({ action: 'scrollPage', value: 'up' })])
    expect(out).toContain('window.scrollBy(0, -window.innerHeight)')
  })

  test('14c. scrollPage by px', () => {
    const out = generateCode([step({ action: 'scrollPage', value: '800' })])
    expect(out).toContain('window.scrollBy(0, 800)')
  })

  test('15. comment is emitted above the step', () => {
    const out = generateCode([step({ action: 'goto', value: 'https://x.com', comment: 'Open twitter' })])
    expect(out).toContain('// Step 1: Open twitter')
  })

  test('15b. no comment → action name used', () => {
    const out = generateCode([step({ action: 'goto', value: 'https://x.com', comment: '' })])
    expect(out).toContain('// Step 1: goto')
  })

  test('16. press key', () => {
    const out = generateCode([step({ action: 'press', selector: '#search', selectorMethod: 'css', value: 'Enter' })])
    expect(out).toContain("await page.press('#search', 'Enter');")
  })

  test('17. selectOption', () => {
    const out = generateCode([step({ action: 'selectOption', selector: 'select#country', selectorMethod: 'css', value: 'US' })])
    expect(out).toContain("await page.selectOption('select#country', 'US');")
  })

  test('18a. check', () => {
    const out = generateCode([step({ action: 'check', selector: '#agree', selectorMethod: 'css' })])
    expect(out).toContain("await page.check('#agree');")
  })

  test('18b. uncheck', () => {
    const out = generateCode([step({ action: 'uncheck', selector: '#agree', selectorMethod: 'css' })])
    expect(out).toContain("await page.uncheck('#agree');")
  })

  test('19. waitForURL', () => {
    const out = generateCode([step({ action: 'waitForURL', value: '**/dashboard**' })])
    expect(out).toContain("await page.waitForURL('**/dashboard**', { timeout: 15000 });")
  })

  test('20. waitForNetIdle', () => {
    const out = generateCode([step({ action: 'waitForNetIdle' })])
    expect(out).toContain("await page.waitForLoadState('networkidle');")
  })

  test('21. log message', () => {
    const out = generateCode([step({ action: 'log', value: 'hello world' })])
    expect(out).toContain("log.info('hello world');")
  })

  test('22. getAttribute', () => {
    const out = generateCode([step({ action: 'getAttribute', selector: 'a.link', selectorMethod: 'css', value: 'href' })])
    expect(out).toContain("const attr_1 = await page.getAttribute('a.link', 'href');")
    expect(out).toContain('log.info(`href: ${attr_1}`);')
  })

  test('23. uploadFile', () => {
    const out = generateCode([step({ action: 'uploadFile', selector: 'input[type="file"]', selectorMethod: 'css', value: '/tmp/file.pdf' })])
    expect(out).toContain("await page.setInputFiles('input[type=\"file\"]', '/tmp/file.pdf');")
  })

  test('24a. reload', () => {
    const out = generateCode([step({ action: 'reload' })])
    expect(out).toContain("await page.reload({ waitUntil: 'domcontentloaded' });")
  })

  test('24b. goBack', () => {
    const out = generateCode([step({ action: 'goBack' })])
    expect(out).toContain('await page.goBack();')
  })

  test('25. multiple steps → blank line separators', () => {
    const out = generateCode([
      step({ action: 'goto', value: 'https://a.com' }),
      step({ action: 'click', selector: 'button', selectorMethod: 'css' }),
    ])
    // Each step ends with an empty line so there should be \n\n between them
    expect(out).toMatch(/page\.goto\(.*\);\n\n.*\/\/ Step 2/)
  })

  test('26. ID selector method builds # prefix', () => {
    const out = generateCode([step({ action: 'click', selector: 'login-btn', selectorMethod: 'id' })])
    expect(out).toContain("await page.click('#login-btn');")
  })

  test('27. fill value with single quote is escaped', () => {
    const out = generateCode([step({ action: 'fill', selector: '#x', selectorMethod: 'css', value: "it's here" })])
    expect(out).toContain("await page.fill('#x', 'it\\'s here');")
  })

  test('28. unknown action → inline comment', () => {
    const out = generateCode([step({ action: 'unknownXYZ' })])
    expect(out).toContain('// [unknown action: unknownXYZ]')
  })

  test('29. getText without value → auto variable name', () => {
    const out = generateCode([step({ action: 'getText', selector: 'h2', selectorMethod: 'css', value: '' })])
    // Should generate text_1 as variable
    expect(out).toContain('const text_1 = await page.textContent')
  })

  test('30. header comment block always present', () => {
    const out = generateCode([step({ action: 'log', value: 'hi' })])
    expect(out).toContain('Auto-generated by ScriptPlayground')
  })
})
